version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "twitter"
    ports:
      - 5432:5432
    volumes:
      - ./resourcers/database:/docker-entrypoint-inidb.d
  
  app:
    build: .
    depends_on: 
      - db
    ports: 
      - 3000:3000

  unit-tests:
    image: clojure:openjdk-17-lein 
    command: lein test 
    volumes: 
      - .:/tmp
